// Object.h

#pragma once

#include <cstdint>
#include <Engine/EngineAPI.h>

// The Object class represents a base class for all objects in the engine. It provides a unique identifier (ID) for each object and a mechanism for marking objects for destruction. The class includes constructors, a destructor, and methods for managing the object's lifecycle and state.
class DEFORM_API Object
{
public:

    // The default constructor is deleted to prevent creating an Object without an ID. This enforces that every Object must have a unique identifier assigned at the time of creation, which is essential for managing objects within the engine.
    Object() = delete;
    // This constructor initializes the Object with a unique identifier (ID). The ID is typically generated by the engine when the object is created and is used to reference the object within the engine's systems. The constructor also initializes the pending destruction flag to false, indicating that the object is not marked for destruction upon creation.
    explicit Object(uint64_t id);

    // The destructor is declared as virtual to allow for proper cleanup of derived classes when an object is destroyed through a base class pointer. This ensures that the destructor of the derived class is called, allowing for any resources allocated by the derived class to be released correctly.
    virtual ~Object() = default;

    // Marks the object for destruction. This method sets a flag indicating that the object should be destroyed at the next available opportunity.
    void Destroy();
    // Checks if the object is marked for destruction. This method returns true if the object is pending destruction, and false otherwise.
    bool GetPendingDestroy() const;

    // Gets the unique identifier (ID) of the object. This ID can be used to reference the object within the engine and is typically assigned when the object is created. The GetID method allows you to retrieve this ID for use in various operations, such as object management, serialization, or debugging.
    uint64_t GetID() const;

private:
    uint64_t m_ID;
    bool m_PendingDestroy;
};